# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 700)
        MainWindow.setMaximumSize(QtCore.QSize(600, 700))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 27))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.StepperMotor = QtWidgets.QDockWidget(MainWindow)
        self.StepperMotor.setMinimumSize(QtCore.QSize(600, 200))
        self.StepperMotor.setObjectName("StepperMotor")
        self.dockWidgetContents_5 = QtWidgets.QWidget()
        self.dockWidgetContents_5.setObjectName("dockWidgetContents_5")
        self.gridLayoutWidget = QtWidgets.QWidget(self.dockWidgetContents_5)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(140, 10, 160, 153))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.XMovementLeft = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.XMovementLeft.setText("")
        icon = QtGui.QIcon.fromTheme("go-previous")
        self.XMovementLeft.setIcon(icon)
        self.XMovementLeft.setIconSize(QtCore.QSize(30, 30))
        self.XMovementLeft.setObjectName("XMovementLeft")
        self.gridLayout_7.addWidget(self.XMovementLeft, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout_7.addWidget(self.label_2, 1, 0, 1, 1)
        self.YMovementUp = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.YMovementUp.setText("")
        icon = QtGui.QIcon.fromTheme("go-up")
        self.YMovementUp.setIcon(icon)
        self.YMovementUp.setIconSize(QtCore.QSize(30, 30))
        self.YMovementUp.setObjectName("YMovementUp")
        self.gridLayout_7.addWidget(self.YMovementUp, 1, 1, 1, 1)
        self.YMovementDown = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.YMovementDown.setText("")
        icon = QtGui.QIcon.fromTheme("go-down")
        self.YMovementDown.setIcon(icon)
        self.YMovementDown.setIconSize(QtCore.QSize(30, 30))
        self.YMovementDown.setObjectName("YMovementDown")
        self.gridLayout_7.addWidget(self.YMovementDown, 3, 1, 1, 1)
        self.XMovementRight = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.XMovementRight.setText("")
        icon = QtGui.QIcon.fromTheme("go-next")
        self.XMovementRight.setIcon(icon)
        self.XMovementRight.setIconSize(QtCore.QSize(30, 30))
        self.XMovementRight.setObjectName("XMovementRight")
        self.gridLayout_7.addWidget(self.XMovementRight, 2, 2, 1, 1)
        self.XYLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.XYLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.XYLabel.setObjectName("XYLabel")
        self.gridLayout_7.addWidget(self.XYLabel, 0, 0, 1, 1)
        self.toolButton_5 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton_5.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("."), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_5.setIcon(icon)
        self.toolButton_5.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_5.setObjectName("toolButton_5")
        self.gridLayout_7.addWidget(self.toolButton_5, 2, 1, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.dockWidgetContents_5)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(290, 10, 161, 153))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.ZLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.ZLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ZLabel.setObjectName("ZLabel")
        self.gridLayout_10.addWidget(self.ZLabel, 0, 0, 1, 1)
        self.ZMovementDown = QtWidgets.QToolButton(self.gridLayoutWidget_2)
        self.ZMovementDown.setText("")
        icon = QtGui.QIcon.fromTheme("go-down")
        self.ZMovementDown.setIcon(icon)
        self.ZMovementDown.setIconSize(QtCore.QSize(30, 30))
        self.ZMovementDown.setObjectName("ZMovementDown")
        self.gridLayout_10.addWidget(self.ZMovementDown, 3, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.gridLayout_10.addWidget(self.label_11, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.gridLayout_10.addWidget(self.label_13, 0, 2, 1, 1)
        self.ZMovementUp = QtWidgets.QToolButton(self.gridLayoutWidget_2)
        self.ZMovementUp.setText("")
        icon = QtGui.QIcon.fromTheme("go-up")
        self.ZMovementUp.setIcon(icon)
        self.ZMovementUp.setIconSize(QtCore.QSize(30, 30))
        self.ZMovementUp.setObjectName("ZMovementUp")
        self.gridLayout_10.addWidget(self.ZMovementUp, 1, 1, 1, 1)
        self.toolButton = QtWidgets.QToolButton(self.gridLayoutWidget_2)
        self.toolButton.setText("")
        self.toolButton.setIconSize(QtCore.QSize(30, 30))
        self.toolButton.setObjectName("toolButton")
        self.gridLayout_10.addWidget(self.toolButton, 2, 1, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.dockWidgetContents_5)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 91, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.StepsPerClickLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.StepsPerClickLabel.setScaledContents(False)
        self.StepsPerClickLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.StepsPerClickLabel.setWordWrap(True)
        self.StepsPerClickLabel.setObjectName("StepsPerClickLabel")
        self.verticalLayout_2.addWidget(self.StepsPerClickLabel)
        self.StepsPerClickSpinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.StepsPerClickSpinBox.setMinimum(1)
        self.StepsPerClickSpinBox.setMaximum(1000)
        self.StepsPerClickSpinBox.setProperty("value", 50)
        self.StepsPerClickSpinBox.setObjectName("StepsPerClickSpinBox")
        self.verticalLayout_2.addWidget(self.StepsPerClickSpinBox)
        self.StepperMotor.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.StepperMotor)
        self.LED = QtWidgets.QDockWidget(MainWindow)
        self.LED.setMinimumSize(QtCore.QSize(600, 125))
        self.LED.setMaximumSize(QtCore.QSize(524287, 125))
        self.LED.setObjectName("LED")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.LEDOn = QtWidgets.QPushButton(self.dockWidgetContents)
        self.LEDOn.setGeometry(QtCore.QRect(9, 9, 91, 30))
        self.LEDOn.setObjectName("LEDOn")
        self.LEDOff = QtWidgets.QPushButton(self.dockWidgetContents)
        self.LEDOff.setGeometry(QtCore.QRect(9, 45, 91, 30))
        self.LEDOff.setObjectName("LEDOff")
        self.LED.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.LED)
        self.Timelapse = QtWidgets.QDockWidget(MainWindow)
        self.Timelapse.setMinimumSize(QtCore.QSize(600, 315))
        self.Timelapse.setObjectName("Timelapse")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.StartTimelapse = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.StartTimelapse.setGeometry(QtCore.QRect(10, 20, 128, 30))
        self.StartTimelapse.setObjectName("StartTimelapse")
        self.label = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.label.setGeometry(QtCore.QRect(10, 60, 76, 22))
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.label_5.setGeometry(QtCore.QRect(10, 140, 181, 22))
        self.label_5.setObjectName("label_5")
        self.framesbox = QtWidgets.QSpinBox(self.dockWidgetContents_2)
        self.framesbox.setGeometry(QtCore.QRect(10, 170, 121, 32))
        self.framesbox.setMinimumSize(QtCore.QSize(121, 32))
        self.framesbox.setMinimum(1)
        self.framesbox.setMaximum(1000000)
        self.framesbox.setProperty("value", 10)
        self.framesbox.setObjectName("framesbox")
        self.label_6 = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.label_6.setGeometry(QtCore.QRect(10, 210, 131, 22))
        self.label_6.setObjectName("label_6")
        self.intervalbox = QtWidgets.QSpinBox(self.dockWidgetContents_2)
        self.intervalbox.setGeometry(QtCore.QRect(10, 240, 121, 32))
        self.intervalbox.setMinimumSize(QtCore.QSize(121, 32))
        self.intervalbox.setMaximum(1000000000)
        self.intervalbox.setProperty("value", 10)
        self.intervalbox.setObjectName("intervalbox")
        self.layoutWidget = QtWidgets.QWidget(self.dockWidgetContents_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 90, 245, 34))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.widthbox = QtWidgets.QSpinBox(self.layoutWidget)
        self.widthbox.setMaximum(4056)
        self.widthbox.setProperty("value", 3280)
        self.widthbox.setObjectName("widthbox")
        self.horizontalLayout.addWidget(self.widthbox)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.heightbox = QtWidgets.QSpinBox(self.layoutWidget)
        self.heightbox.setMaximum(3040)
        self.heightbox.setProperty("value", 2464)
        self.heightbox.setObjectName("heightbox")
        self.horizontalLayout.addWidget(self.heightbox)
        self.filename = QtWidgets.QLineEdit(self.dockWidgetContents_2)
        self.filename.setGeometry(QtCore.QRect(210, 170, 311, 30))
        self.filename.setObjectName("filename")
        self.browse = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.browse.setGeometry(QtCore.QRect(530, 170, 61, 30))
        self.browse.setObjectName("browse")
        self.label_7 = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.label_7.setGeometry(QtCore.QRect(210, 140, 181, 22))
        self.label_7.setObjectName("label_7")
        self.startpreview = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.startpreview.setGeometry(QtCore.QRect(210, 20, 161, 30))
        self.startpreview.setObjectName("startpreview")
        self.stoppreview = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.stoppreview.setGeometry(QtCore.QRect(390, 20, 161, 30))
        self.stoppreview.setObjectName("stoppreview")
        self.Timelapse.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.Timelapse)
        self.actionIDS_Camera = QtWidgets.QAction(MainWindow)
        self.actionIDS_Camera.setCheckable(True)
        self.actionIDS_Camera.setChecked(True)
        self.actionIDS_Camera.setObjectName("actionIDS_Camera")
        self.actionRaspberry_Pi_Camera = QtWidgets.QAction(MainWindow)
        self.actionRaspberry_Pi_Camera.setCheckable(True)
        self.actionRaspberry_Pi_Camera.setChecked(True)
        self.actionRaspberry_Pi_Camera.setObjectName("actionRaspberry_Pi_Camera")
        self.actionStepper_Motor_Stage_Control = QtWidgets.QAction(MainWindow)
        self.actionStepper_Motor_Stage_Control.setCheckable(True)
        self.actionStepper_Motor_Stage_Control.setChecked(True)
        self.actionStepper_Motor_Stage_Control.setObjectName("actionStepper_Motor_Stage_Control")
        self.actionIDS_Camera_Video = QtWidgets.QAction(MainWindow)
        self.actionIDS_Camera_Video.setCheckable(True)
        self.actionIDS_Camera_Video.setChecked(True)
        self.actionIDS_Camera_Video.setObjectName("actionIDS_Camera_Video")
        self.actionRaspberry_Pi_Camera_Video = QtWidgets.QAction(MainWindow)
        self.actionRaspberry_Pi_Camera_Video.setCheckable(True)
        self.actionRaspberry_Pi_Camera_Video.setChecked(True)
        self.actionRaspberry_Pi_Camera_Video.setObjectName("actionRaspberry_Pi_Camera_Video")
        self.menuView.addAction(self.actionStepper_Motor_Stage_Control)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        self.StepperMotor.visibilityChanged['bool'].connect(self.actionStepper_Motor_Stage_Control.setChecked)
        self.actionStepper_Motor_Stage_Control.triggered['bool'].connect(self.StepperMotor.setVisible)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.StepperMotor.setWindowTitle(_translate("MainWindow", "Stepper Motor Stage Control"))
        self.XYLabel.setText(_translate("MainWindow", "XY"))
        self.ZLabel.setText(_translate("MainWindow", "Z"))
        self.StepsPerClickLabel.setText(_translate("MainWindow", "Number of Steps Per Click"))
        self.LED.setWindowTitle(_translate("MainWindow", "LED Control"))
        self.LEDOn.setText(_translate("MainWindow", "LED On"))
        self.LEDOff.setText(_translate("MainWindow", "LED Off"))
        self.Timelapse.setWindowTitle(_translate("MainWindow", "Timelapse Settings and Control"))
        self.StartTimelapse.setText(_translate("MainWindow", "Start Timelapse"))
        self.label.setText(_translate("MainWindow", "Resolution"))
        self.label_5.setText(_translate("MainWindow", "Total Number of Frames"))
        self.label_6.setText(_translate("MainWindow", "Interval (seconds)"))
        self.label_3.setText(_translate("MainWindow", "Width"))
        self.label_4.setText(_translate("MainWindow", "Height"))
        self.browse.setText(_translate("MainWindow", "Browse"))
        self.label_7.setText(_translate("MainWindow", "Save Directory"))
        self.startpreview.setText(_translate("MainWindow", "Start Camera Preview"))
        self.stoppreview.setText(_translate("MainWindow", "Stop Camera Preview"))
        self.actionIDS_Camera.setText(_translate("MainWindow", "IDS Camera"))
        self.actionRaspberry_Pi_Camera.setText(_translate("MainWindow", "Raspberry Pi Camera"))
        self.actionStepper_Motor_Stage_Control.setText(_translate("MainWindow", "Stepper Motor Stage Control"))
        self.actionIDS_Camera_Video.setText(_translate("MainWindow", "IDS Camera Video"))
        self.actionRaspberry_Pi_Camera_Video.setText(_translate("MainWindow", "Raspberry Pi Camera Video"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

